### ISSUE TITLE
Provide API for random numbers/bytes

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-java#17]
Service invocations could provide a `Random` implementation which is seeded with the invocation id. Given that the invocation id is an `UUID` this might give enough entropy for non-cryptographic uses cases. Moreover, it allows to deterministically generate the random values across retries and suspension points.

We could start simple by providing a `RestateRandom` that only generates random bytes.

```java
interface RestateRandom {
    // Fills the given bytes array with random bytes
    public void nextBytes(byte[] bytes);
}
```

**Comment by slinkydeveloper** [comment]
Superseded by https://github.com/restatedev/sdk-java/issues/155
