### ISSUE TITLE
Reduce copying of `byte[]`/`ByteString` by introducing `Slice` type

### ISSUE THREAD

**Issue by tillrohrmann** [restatedev/sdk-java#18]
It might be possible to reduce copying of `byte[]` (from and to `ByteString`) by introducing a `Slice` type similar to how `statefun-java-sdk` does it.

References:
* https://github.com/apache/flink-statefun/blob/master/statefun-sdk-java/src/main/java/org/apache/flink/statefun/sdk/java/slice/Slice.java
* https://github.com/apache/flink-statefun/blob/38f5518f26f96387f0c266531b6ef2c3fd0df729/statefun-sdk-java/src/main/java/org/apache/flink/statefun/sdk/java/slice/Slices.java#L37
* https://github.com/apache/flink-statefun/blob/master/statefun-sdk-java/src/main/java/org/apache/flink/statefun/sdk/java/slice/SliceProtobufUtil.java

**Comment by slinkydeveloper** [comment]
We now use `ByteBuffer`, this is good.
