### ISSUE TITLE
[Java] Ensure Restate context attributes are applied to handler-emitted log4j log entries 

### ISSUE THREAD

**Issue by pcholakov** [restatedev/sdk-java#180]
With the removal of `GrpcContextDataProvider` in https://github.com/restatedev/sdk-java/pull/179 we no longer preserve the Restate operation name and invocation id into customer calls across threads in Java, though this still works for Kotlin code. We made this tradeoff to fix a different issue in AWS Lambda, that was related to the custom context provider.

Objective: restore the functionality where handler-logged entries are properly annotated with Restate context.

**Comment by slinkydeveloper** [comment]
To fix this properly we need to reintroduce the `ContextDataProvider` we had before. We should also wrap the invocation status into something like `RestateInvocationContext`, which we propagate through grpc Context for the time being due to the generated code.
