### ISSUE TITLE
Remove logging of InvocationStateMachine ByteString ids

### ISSUE THREAD

**Issue by gvdongen** [restatedev/sdk-java#281]
The logs for the InvocationStateMachine contain a lot of noise due to the ByteString id:
`Transitioning InvocationStateMachine{id=<ByteString@20d1b148 size=24 contents="\301\254\001\352\255\357%\020\001\216\322U\223<\323\301\337\246E6n\031\276\225">} to REPLAYING`

**Comment by slinkydeveloper** [comment]
Fixed
