### ISSUE TITLE
Awakeable handle annotated with `@NotNull` but needs `null` for VOID types

### ISSUE THREAD

**Issue by StephanEwen** [restatedev/sdk-java#357]
For VOID typed awakeables, the value passed during resolution is `null` but the handler is annotated to not accept that.

![image](https://github.com/restatedev/sdk-java/assets/1727146/e663cde7-cdda-4f7e-bbe3-d4654f32c8c2)

**Comment by slinkydeveloper** [comment]
Unfortunately I don't really have a good solution that solves it with the nullness annotations. I see two ways of solving this:

* Either have a variant `resolve()` without arguments.
* Or have some marker unit value (a-la kotlin `Unit), e.g. `Unit.INSTANCE` or something like that.

I think I'll go with the former

**Comment by slinkydeveloper** [comment]
Perhaps this `@NonNull` is indeed too restrictive to begin with. I'll remove it for the time being.

**Comment by slinkydeveloper** [comment]
I've figured that with JSpecify I can enforce this directly on the `Serde` annotation, and not on the individual context methods. Working on this now.
